2025-10-05 14:21:31.192 | WARNING  | users.helpers.errors.global_handler_error:process_exception:17 - Handled AppError: bad_request Invalid data {'extra': {'name': [ErrorDetail(string='This field is required.', code='required')], 'last_name': [ErrorDetail(string='This field is required.', code='required')], 'confirm_password': [ErrorDetail(string='This field is required.', code='required')]}, 'path': '/api/v1/users/'}
2025-10-05 14:28:42.471 | WARNING  | users.helpers.errors.global_handler_error:process_exception:17 - Handled AppError: unathorized Invalid credentials {'extra': None, 'path': '/api/v1/login/'}
2025-10-05 14:28:55.973 | ERROR    | users.helpers.errors.global_handler_error:process_exception:36 - Unhandled exception on request /api/v1/login/: Traceback (most recent call last):
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\projectos\empresa\yhanko\ecomerce\users\views.py", line 31, in post
    token = self.auth_service.create_access_token(user.id)
  File "C:\projectos\empresa\yhanko\ecomerce\users\services\auth_service.py", line 30, in create_access_token
    "exp": now + timedelta(seconds=settings.JWT_EXP_SECONDS),
                 ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unsupported type for timedelta seconds component: str

Traceback (most recent call last):

  File "C:\Python313\Lib\threading.py", line 1012, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x00000196CD5D49A0>
    └ <Thread(Thread-2 (process_request_thread), started daemon 6544)>
  File "C:\Python313\Lib\threading.py", line 1041, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x00000196CD5D4720>
    └ <Thread(Thread-2 (process_request_thread), started daemon 6544)>
  File "C:\Python313\Lib\threading.py", line 992, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-2 (process_request_thread), started daemon 6544)>
    │    │        │    └ (<socket.socket fd=1096, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 8472)>, ('127.0.0.1', 8472))
    │    │        └ <Thread(Thread-2 (process_request_thread), started daemon 6544)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x00000196D224B4D0>>
    └ <Thread(Thread-2 (process_request_thread), started daemon 6544)>
  File "C:\Python313\Lib\socketserver.py", line 697, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 8472)
    │    │              └ <socket.socket fd=1096, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 8472)>
    │    └ <function BaseServer.finish_request at 0x00000196D0978C20>
    └ <django.core.servers.basehttp.WSGIServer object at 0x00000196D224B4D0>
  File "C:\Python313\Lib\socketserver.py", line 362, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x00000196D224B4D0>
    │    │                   │        └ ('127.0.0.1', 8472)
    │    │                   └ <socket.socket fd=1096, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 8472)>
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x00000196D224B4D0>
  File "C:\Python313\Lib\socketserver.py", line 766, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x00000196D1ED2980>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x00000196D22C5950>
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\django\core\servers\basehttp.py", line 228, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x00000196D1ED2A20>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x00000196D22C5950>
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\django\core\servers\basehttp.py", line 253, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x00000196D1ED1940>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x00000196D224B4D0>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x00000196D22C5950>
    │       └ <function BaseHandler.run at 0x00000196D1EC1120>
    └ <django.core.servers.basehttp.ServerHandler object at 0x00000196D22C6710>
  File "C:\Python313\Lib\wsgiref\handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x00000196D1EC14E0>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x00000196D22C6710>
    │    │        │           │    └ {'ALLUSERSPROFILE': 'C:\\ProgramData', 'APPDATA': 'C:\\Users\\Romeu\\AppData\\Roaming', 'BUNDLED_DEBUGPY_PATH': 'c:\\Users\\R...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x00000196D22C6710>
    │    │        └ <django.contrib.staticfiles.handlers.StaticFilesHandler object at 0x00000196D224B620>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x00000196D22C6710>
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\django\contrib\staticfiles\handlers.py", line 80, in __call__
    return self.application(environ, start_response)
           │    │           │        └ <bound method BaseHandler.start_response of <django.core.servers.basehttp.ServerHandler object at 0x00000196D22C6710>>
           │    │           └ {'ALLUSERSPROFILE': 'C:\\ProgramData', 'APPDATA': 'C:\\Users\\Romeu\\AppData\\Roaming', 'BUNDLED_DEBUGPY_PATH': 'c:\\Users\\R...
           │    └ <django.core.handlers.wsgi.WSGIHandler object at 0x00000196D0933770>
           └ <django.contrib.staticfiles.handlers.StaticFilesHandler object at 0x00000196D224B620>
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\django\core\handlers\wsgi.py", line 124, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: POST '/api/v1/login/'>
               │    └ <function BaseHandler.get_response at 0x00000196D1E32480>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x00000196D0933770>
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\django\core\handlers\base.py", line 140, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: POST '/api/v1/login/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x00000196D0A0CC20>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x00000196D0933770>
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               │            └ <WSGIRequest: POST '/api/v1/login/'>
               └ <GlobalExceptionMiddleware get_response=convert_exception_to_response.<locals>.inner>
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\django\utils\deprecation.py", line 120, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: POST '/api/v1/login/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x00000196D0A0CB80>
               │           └ <GlobalExceptionMiddleware get_response=convert_exception_to_response.<locals>.inner>
               └ None
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               │            └ <WSGIRequest: POST '/api/v1/login/'>
               └ <SecurityMiddleware get_response=convert_exception_to_response.<locals>.inner>
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\django\utils\deprecation.py", line 120, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: POST '/api/v1/login/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x00000196D0A0CD60>
               │           └ <SecurityMiddleware get_response=convert_exception_to_response.<locals>.inner>
               └ None
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               │            └ <WSGIRequest: POST '/api/v1/login/'>
               └ <SessionMiddleware get_response=convert_exception_to_response.<locals>.inner>
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\django\utils\deprecation.py", line 120, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: POST '/api/v1/login/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x00000196D0A0CE00>
               │           └ <SessionMiddleware get_response=convert_exception_to_response.<locals>.inner>
               └ None
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               │            └ <WSGIRequest: POST '/api/v1/login/'>
               └ <CommonMiddleware get_response=convert_exception_to_response.<locals>.inner>
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\django\utils\deprecation.py", line 120, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: POST '/api/v1/login/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x00000196D0A0CEA0>
               │           └ <CommonMiddleware get_response=convert_exception_to_response.<locals>.inner>
               └ None
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               │            └ <WSGIRequest: POST '/api/v1/login/'>
               └ <CsrfViewMiddleware get_response=convert_exception_to_response.<locals>.inner>
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\django\utils\deprecation.py", line 120, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: POST '/api/v1/login/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x00000196D0A0CF40>
               │           └ <CsrfViewMiddleware get_response=convert_exception_to_response.<locals>.inner>
               └ None
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               │            └ <WSGIRequest: POST '/api/v1/login/'>
               └ <AuthenticationMiddleware get_response=convert_exception_to_response.<locals>.inner>
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\django\utils\deprecation.py", line 120, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: POST '/api/v1/login/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x00000196D0A0CFE0>
               │           └ <AuthenticationMiddleware get_response=convert_exception_to_response.<locals>.inner>
               └ None
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               │            └ <WSGIRequest: POST '/api/v1/login/'>
               └ <MessageMiddleware get_response=convert_exception_to_response.<locals>.inner>
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\django\utils\deprecation.py", line 120, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: POST '/api/v1/login/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x00000196D0A0D080>
               │           └ <MessageMiddleware get_response=convert_exception_to_response.<locals>.inner>
               └ None
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               │            └ <WSGIRequest: POST '/api/v1/login/'>
               └ <XFrameOptionsMiddleware get_response=BaseHandler._get_response>
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\django\utils\deprecation.py", line 120, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: POST '/api/v1/login/'>
               │           │    └ <function BaseHandler._get_response at 0x00000196D0A0C680>
               │           └ <XFrameOptionsMiddleware get_response=BaseHandler._get_response>
               └ None
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               │            └ <WSGIRequest: POST '/api/v1/login/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x00000196D0933770>>
> File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {}
               │                │         └ ()
               │                └ <WSGIRequest: POST '/api/v1/login/'>
               └ <function View.as_view.<locals>.view at 0x00000196D1F36E80>
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           │         │         │       └ {}
           │         │         └ ()
           │         └ <WSGIRequest: POST '/api/v1/login/'>
           └ <function View.as_view.<locals>.view at 0x00000196D1F34180>
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           │    │        │         │       └ {}
           │    │        │         └ ()
           │    │        └ <WSGIRequest: POST '/api/v1/login/'>
           │    └ <function APIView.dispatch at 0x00000196D2143EC0>
           └ <users.views.LoginView object at 0x00000196D22C79D0>
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               │    └ <function APIView.handle_exception at 0x00000196D2143D80>
               └ <users.views.LoginView object at 0x00000196D22C79D0>
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    │    │                        └ TypeError('unsupported type for timedelta seconds component: str')
    │    └ <function APIView.raise_uncaught_exception at 0x00000196D2143E20>
    └ <users.views.LoginView object at 0x00000196D22C79D0>
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
          └ TypeError('unsupported type for timedelta seconds component: str')
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               │       │         │       └ {}
               │       │         └ ()
               │       └ <rest_framework.request.Request: POST '/api/v1/login/'>
               └ <bound method LoginView.post of <users.views.LoginView object at 0x00000196D22C79D0>>

  File "C:\projectos\empresa\yhanko\ecomerce\users\views.py", line 31, in post
    token = self.auth_service.create_access_token(user.id)
            │    │            │                   │    └ '09e7a6f6-b1ec-469a-836e-10ee778385b3'
            │    │            │                   └ UserEntity(id='09e7a6f6-b1ec-469a-836e-10ee778385b3', name='Romeu', last_name='Cajamba', email='romeucajamba@gmail.com', pass...
            │    │            └ <function AuthService.create_access_token at 0x00000196D2229080>
            │    └ <users.services.auth_service.AuthService object at 0x00000196D22C7B10>
            └ <users.views.LoginView object at 0x00000196D22C79D0>

  File "C:\projectos\empresa\yhanko\ecomerce\users\services\auth_service.py", line 30, in create_access_token
    "exp": now + timedelta(seconds=settings.JWT_EXP_SECONDS),
           │     │                 │        └ '3600'
           │     │                 └ <LazySettings "api.settings">
           │     └ <class 'datetime.timedelta'>
           └ datetime.datetime(2025, 10, 5, 14, 28, 55, 906983)

TypeError: unsupported type for timedelta seconds component: str
2025-10-05 14:34:05.230 | ERROR    | users.helpers.errors.global_handler_error:process_exception:36 - Unhandled exception on request /api/v1/login/: Traceback (most recent call last):
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\projectos\empresa\yhanko\ecomerce\users\views.py", line 31, in post
    token = self.auth_service.create_access_token(user.id)
  File "C:\projectos\empresa\yhanko\ecomerce\users\services\auth_service.py", line 30, in create_access_token
    "exp": now + timedelta(seconds=settings.JWT_EXP_SECONDS),
                 ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unsupported type for timedelta seconds component: str

Traceback (most recent call last):

  File "C:\Python313\Lib\threading.py", line 1012, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x0000016C10CE49A0>
    └ <Thread(Thread-1 (process_request_thread), started daemon 12824)>
  File "C:\Python313\Lib\threading.py", line 1041, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x0000016C10CE4720>
    └ <Thread(Thread-1 (process_request_thread), started daemon 12824)>
  File "C:\Python313\Lib\threading.py", line 992, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1 (process_request_thread), started daemon 12824)>
    │    │        │    └ (<socket.socket fd=1060, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 7491)>, ('127.0.0.1', 7491))
    │    │        └ <Thread(Thread-1 (process_request_thread), started daemon 12824)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x0000016C159D74D0>>
    └ <Thread(Thread-1 (process_request_thread), started daemon 12824)>
  File "C:\Python313\Lib\socketserver.py", line 697, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 7491)
    │    │              └ <socket.socket fd=1060, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 7491)>
    │    └ <function BaseServer.finish_request at 0x0000016C14108C20>
    └ <django.core.servers.basehttp.WSGIServer object at 0x0000016C159D74D0>
  File "C:\Python313\Lib\socketserver.py", line 362, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x0000016C159D74D0>
    │    │                   │        └ ('127.0.0.1', 7491)
    │    │                   └ <socket.socket fd=1060, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 7491)>
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x0000016C159D74D0>
  File "C:\Python313\Lib\socketserver.py", line 766, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x0000016C1565E980>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x0000016C159D6E40>
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\django\core\servers\basehttp.py", line 228, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x0000016C1565EA20>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x0000016C159D6E40>
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\django\core\servers\basehttp.py", line 253, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x0000016C1565D940>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x0000016C159D74D0>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x0000016C159D6E40>
    │       └ <function BaseHandler.run at 0x0000016C1564D120>
    └ <django.core.servers.basehttp.ServerHandler object at 0x0000016C159D6CF0>
  File "C:\Python313\Lib\wsgiref\handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x0000016C1564D4E0>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x0000016C159D6CF0>
    │    │        │           │    └ {'ALLUSERSPROFILE': 'C:\\ProgramData', 'APPDATA': 'C:\\Users\\Romeu\\AppData\\Roaming', 'BUNDLED_DEBUGPY_PATH': 'c:\\Users\\R...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x0000016C159D6CF0>
    │    │        └ <django.contrib.staticfiles.handlers.StaticFilesHandler object at 0x0000016C159D7620>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x0000016C159D6CF0>
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\django\contrib\staticfiles\handlers.py", line 80, in __call__
    return self.application(environ, start_response)
           │    │           │        └ <bound method BaseHandler.start_response of <django.core.servers.basehttp.ServerHandler object at 0x0000016C159D6CF0>>
           │    │           └ {'ALLUSERSPROFILE': 'C:\\ProgramData', 'APPDATA': 'C:\\Users\\Romeu\\AppData\\Roaming', 'BUNDLED_DEBUGPY_PATH': 'c:\\Users\\R...
           │    └ <django.core.handlers.wsgi.WSGIHandler object at 0x0000016C140C3770>
           └ <django.contrib.staticfiles.handlers.StaticFilesHandler object at 0x0000016C159D7620>
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\django\core\handlers\wsgi.py", line 124, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: POST '/api/v1/login/'>
               │    └ <function BaseHandler.get_response at 0x0000016C155C2480>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x0000016C140C3770>
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\django\core\handlers\base.py", line 140, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: POST '/api/v1/login/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x0000016C141A0B80>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x0000016C140C3770>
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               │            └ <WSGIRequest: POST '/api/v1/login/'>
               └ <GlobalExceptionMiddleware get_response=convert_exception_to_response.<locals>.inner>
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\django\utils\deprecation.py", line 120, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: POST '/api/v1/login/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x0000016C141A0CC0>
               │           └ <GlobalExceptionMiddleware get_response=convert_exception_to_response.<locals>.inner>
               └ None
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               │            └ <WSGIRequest: POST '/api/v1/login/'>
               └ <SecurityMiddleware get_response=convert_exception_to_response.<locals>.inner>
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\django\utils\deprecation.py", line 120, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: POST '/api/v1/login/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x0000016C141A0D60>
               │           └ <SecurityMiddleware get_response=convert_exception_to_response.<locals>.inner>
               └ None
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               │            └ <WSGIRequest: POST '/api/v1/login/'>
               └ <SessionMiddleware get_response=convert_exception_to_response.<locals>.inner>
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\django\utils\deprecation.py", line 120, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: POST '/api/v1/login/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x0000016C141A0E00>
               │           └ <SessionMiddleware get_response=convert_exception_to_response.<locals>.inner>
               └ None
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               │            └ <WSGIRequest: POST '/api/v1/login/'>
               └ <CommonMiddleware get_response=convert_exception_to_response.<locals>.inner>
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\django\utils\deprecation.py", line 120, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: POST '/api/v1/login/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x0000016C141A0EA0>
               │           └ <CommonMiddleware get_response=convert_exception_to_response.<locals>.inner>
               └ None
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               │            └ <WSGIRequest: POST '/api/v1/login/'>
               └ <CsrfViewMiddleware get_response=convert_exception_to_response.<locals>.inner>
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\django\utils\deprecation.py", line 120, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: POST '/api/v1/login/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x0000016C141A0F40>
               │           └ <CsrfViewMiddleware get_response=convert_exception_to_response.<locals>.inner>
               └ None
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               │            └ <WSGIRequest: POST '/api/v1/login/'>
               └ <AuthenticationMiddleware get_response=convert_exception_to_response.<locals>.inner>
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\django\utils\deprecation.py", line 120, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: POST '/api/v1/login/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x0000016C141A0FE0>
               │           └ <AuthenticationMiddleware get_response=convert_exception_to_response.<locals>.inner>
               └ None
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               │            └ <WSGIRequest: POST '/api/v1/login/'>
               └ <MessageMiddleware get_response=convert_exception_to_response.<locals>.inner>
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\django\utils\deprecation.py", line 120, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: POST '/api/v1/login/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x0000016C141A1080>
               │           └ <MessageMiddleware get_response=convert_exception_to_response.<locals>.inner>
               └ None
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               │            └ <WSGIRequest: POST '/api/v1/login/'>
               └ <XFrameOptionsMiddleware get_response=BaseHandler._get_response>
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\django\utils\deprecation.py", line 120, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: POST '/api/v1/login/'>
               │           │    └ <function BaseHandler._get_response at 0x0000016C141A0680>
               │           └ <XFrameOptionsMiddleware get_response=BaseHandler._get_response>
               └ None
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               │            └ <WSGIRequest: POST '/api/v1/login/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x0000016C140C3770>>
> File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {}
               │                │         └ ()
               │                └ <WSGIRequest: POST '/api/v1/login/'>
               └ <function View.as_view.<locals>.view at 0x0000016C1566C4A0>
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           │         │         │       └ {}
           │         │         └ ()
           │         └ <WSGIRequest: POST '/api/v1/login/'>
           └ <function View.as_view.<locals>.view at 0x0000016C1566EC00>
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           │    │        │         │       └ {}
           │    │        │         └ ()
           │    │        └ <WSGIRequest: POST '/api/v1/login/'>
           │    └ <function APIView.dispatch at 0x0000016C158D3EC0>
           └ <users.views.LoginView object at 0x0000016C15A560D0>
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               │    └ <function APIView.handle_exception at 0x0000016C158D3D80>
               └ <users.views.LoginView object at 0x0000016C15A560D0>
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    │    │                        └ TypeError('unsupported type for timedelta seconds component: str')
    │    └ <function APIView.raise_uncaught_exception at 0x0000016C158D3E20>
    └ <users.views.LoginView object at 0x0000016C15A560D0>
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
          └ TypeError('unsupported type for timedelta seconds component: str')
  File "C:\projectos\empresa\yhanko\ecomerce\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               │       │         │       └ {}
               │       │         └ ()
               │       └ <rest_framework.request.Request: POST '/api/v1/login/'>
               └ <bound method LoginView.post of <users.views.LoginView object at 0x0000016C15A560D0>>

  File "C:\projectos\empresa\yhanko\ecomerce\users\views.py", line 31, in post
    token = self.auth_service.create_access_token(user.id)
            │    │            │                   │    └ '09e7a6f6-b1ec-469a-836e-10ee778385b3'
            │    │            │                   └ UserEntity(id='09e7a6f6-b1ec-469a-836e-10ee778385b3', name='Romeu', last_name='Cajamba', email='romeucajamba@gmail.com', pass...
            │    │            └ <function AuthService.create_access_token at 0x0000016C159B5080>
            │    └ <users.services.auth_service.AuthService object at 0x0000016C15A56350>
            └ <users.views.LoginView object at 0x0000016C15A560D0>

  File "C:\projectos\empresa\yhanko\ecomerce\users\services\auth_service.py", line 30, in create_access_token
    "exp": now + timedelta(seconds=settings.JWT_EXP_SECONDS),
           │     │                 │        └ '3600'
           │     │                 └ <LazySettings "api.settings">
           │     └ <class 'datetime.timedelta'>
           └ datetime.datetime(2025, 10, 5, 14, 34, 5, 225174)

TypeError: unsupported type for timedelta seconds component: str
2025-10-05 14:39:08.089 | INFO     | users.views:post:51 - User logged in: romeucajamba@gmail.com
